@API_HostAddress = http://localhost:5198
@Token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidGVzdDFAdGVzdC5jb20iLCJqdGkiOiI4NDM2MWVmMS02MDg1LTQwMzQtOTllMC0xNjVkYzU1MTc5ZDAiLCJleHAiOjE3MjEwNDY5MzQsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTE5OCIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTAwMCJ9.6ID9tYsF6cVM-igdKz3c_TLQppoEAlLI29HS9kgkcRg
GET {{API_HostAddress}}/api/Employee/
Accept: application/json
Authorization: Bearer {{Token}}

###
POST {{API_HostAddress}}/api/Account/signup/
Accept: application/json
Content-Type: application/json

{
  "Email": "test1@test.com",
  "Password": "Test@123",   
  "ConfirmPassword" :"Test@123"
}

### 

POST {{API_HostAddress}}/api/Account/signin/
Accept: application/json
Content-Type: application/json

{
  "Email": "test1@test.com",
  "Password": "Test@123"
}

### 